### ISSUE TITLE
volume doesnt get upated

### ISSUE THREAD

**Issue by lyogavin** [pegatron89/smartthingstv#2]
Hi,

Thanks for putting together this.

I tried your implementation, my volume and mute status doesn't update. I tried put a refresh before status call, the refresh gives me :{"code":"UnexpectedError","message":"unsuccessful-http-call status=400","details":[]}}.

Have you seen this? Can you get updated volume and mute status? Do you know any other thing I can try? My TV is NU800

**Comment by jaruba** [comment]
It looks like you're getting a `400` http error, which means: `Bad Request`.

Maybe you didn't select all the required permissions for this component when creating the Access Token?

**Comment by jaruba** [comment]
Oh, there was also a PR that was merged 9 hours ago that fixes getting the volume level, I guess you tested this after the PR was merged?

**Comment by pegatron89** [comment]
Does anything else update? Like the current source or state?

I just tried it again there and works ok
